server:
  port: 80
  forward-headers-strategy: native

spring:
  application:
    name: come-together-planner
  main:
    banner-mode: off
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:./data/cometogether
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

app:
  admin:
    password: "super-secret-password"
